name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  build:
  
    runs-on: ubuntu-20.04
  
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'

      - run: mvn package --file pom.xml
      
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/
